version: '3.8'

services:
  # 1. API Python
  iota-messages-api:
    build: ./iota-messages-api
    container_name: iota-messages-api
    restart: unless-stopped
    ports:
      - "5555:5555"
    networks:
      - iota-net

  # 2. Broker Mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    command: mosquitto -c /mosquitto-no-auth.conf
    networks:
      - iota-net

  # 3. IOTA Hornet (Nodo)
  iota-hornet:
    image: iotaledger/hornet:2.0
    container_name: iota-hornet
    ports:
      - "30506:15600"
      - "14265:14265"
      - "9029:9029"
      - "6011:6060/tcp"
    volumes:
      - ./iota-tangle/config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./iota-tangle/docker/main/privatedb/hornet:/app/privatedb
      - ./iota-tangle/docker/main/snapshots/hornet:/app/snapshots
    command: 
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=hornet-node"
      - "--inx.enabled=true"
      - "--inx.bindAddress=0.0.0.0:9029"
      - "--debug.enabled=true"
    networks:
      - iota-net

  # 4. IOTA INX Coordinator
  inx-coordinator:
    container_name: inx-coordinator
    image: iotaledger/inx-coordinator:1.0
    depends_on:
      - iota-hornet
    environment:
      - "COO_PRV_KEYS=e22c9c88a83333a27b4101d7203d7b122bdd73be7bfc75933adf90c829c2b6520cbc8c101dfb83f2129809cb4ad6146593fb71df4a7dbd787c64db6b78529b86,d1f9414a7435a9cbc1f0ff9048d537fb9469f7bef69d5eb88f0c9311bc010115d533b349c7b45b039d36aee7789a29364ed24119ec8306aef71b808b40020ee9"
    ports:
      - "6021:6060/tcp"
    volumes:
      - ./iota-tangle/docker/main/privatedb/state:/app/state
    command:
      - "--inx.address=iota-hornet:9029"
      - "--coordinator.stateFilePath=state/coordinator.state"
      - "--coordinator.blockBackups.enabled=false"
    networks:
      - iota-net

  # 5. IOTA INX Dashboard
  iota-inx-dashboard:
    image: iotaledger/inx-dashboard:1.0
    container_name: iota-inx-dashboard
    depends_on:
      - iota-hornet
    ports:
      - "31031:6060"
      - "31011:8081"
    command: 
      - "--inx.address=iota-hornet:9029"
      - "--dashboard.bindAddress=0.0.0.0:8081"
      - "--dashboard.auth.passwordHash=187ec12c64d869e3e2316a59215f5d8b4e2e225742d5e2d13535d3974f746023"
      - "--dashboard.auth.passwordSalt=d1aee8e5700f458d0f799f7643c12bdd83c964c6cc31b4db60565598cc54a91c"
      - "--prometheus.enabled=false"
    networks:
      - iota-net

networks:
  iota-net:
    driver: bridge